services:
  db:
    image: postgres
    restart: always
    environment:
      args:
        POSTGRES_USER: process.env.POSTGRES_USER
        POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD
        POSTGRES_DATABASE: process.env.POSTGRES_DATABASE
    ports:
      - 5432:5432
